### ISSUE TITLE
Problems on installing the required Python packages. error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Yujie29800** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#51]
Hello Stefanie,

I have been reading your book recently, and after I set up the virtual environment using venv, I can not install the requirements.txt,  It seems like the problem is about "Getting requirements to build wheel did not run successfully." 

yujie@192 ~ % cd /Users/yujie/Coding 
yujie@192 Coding % source myenv/bin/activate
(myenv) yujie@192 Coding % pip install -r requirements.txt
Collecting git+https://github.com/stefmolin/login-attempt-simulator.git@2nd_edition (from -r requirements.txt (line 15))
  Cloning https://github.com/stefmolin/login-attempt-simulator.git (to revision 2nd_edition) to /private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-req-build-4wu5vntn
  Running command git clone --filter=blob:none --quiet https://github.com/stefmolin/login-attempt-simulator.git /private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-req-build-4wu5vntn
  Running command git checkout -q 76e065a122343ebdd51c1cae98fbb8285411c0ff
  Resolved https://github.com/stefmolin/login-attempt-simulator.git to commit 76e065a122343ebdd51c1cae98fbb8285411c0ff
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/stefmolin/ml-utils.git@2nd_edition (from -r requirements.txt (line 16))
  Cloning https://github.com/stefmolin/ml-utils.git (to revision 2nd_edition) to /private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-req-build-w6xgtj87
  Running command git clone --filter=blob:none --quiet https://github.com/stefmolin/ml-utils.git /private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-req-build-w6xgtj87
  Running command git checkout -q 90ec708f1b9333a47c29d6b5a1fef13f409fbaea
  Resolved https://github.com/stefmolin/ml-utils.git to commit 90ec708f1b9333a47c29d6b5a1fef13f409fbaea
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/stefmolin/stock-analysis.git@2nd_edition (from -r requirements.txt (line 17))
  Cloning https://github.com/stefmolin/stock-analysis.git (to revision 2nd_edition) to /private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-req-build-brltnduj
  Running command git clone --filter=blob:none --quiet https://github.com/stefmolin/stock-analysis.git /private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-req-build-brltnduj
  Running command git checkout -q a85af035178626c655d1ba04fd51ff6a4461a113
  Resolved https://github.com/stefmolin/stock-analysis.git to commit a85af035178626c655d1ba04fd51ff6a4461a113
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Processing ./visual-aids
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting graphviz==0.14.1 (from -r requirements.txt (line 1))
  Downloading graphviz-0.14.1-py2.py3-none-any.whl.metadata (6.7 kB)
Collecting imbalanced-learn==0.7.0 (from -r requirements.txt (line 2))
  Downloading imbalanced_learn-0.7.0-py3-none-any.whl.metadata (11 kB)
Collecting ipympl==0.6.2 (from -r requirements.txt (line 3))
  Downloading ipympl-0.6.2-py2.py3-none-any.whl.metadata (928 bytes)
Collecting jupyterlab<=3.5.3,>=3.0.4 (from -r requirements.txt (line 4))
  Downloading jupyterlab-3.5.3-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib==3.3.2 (from -r requirements.txt (line 5))
  Downloading matplotlib-3.3.2.tar.gz (37.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 9.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      <string>:32: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************
      
      !!
      Traceback (most recent call last):
        File "/Users/yujie/Coding/myenv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/yujie/Coding/myenv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/yujie/Coding/myenv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-build-env-8jqrm665/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-build-env-8jqrm665/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-build-env-8jqrm665/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-build-env-8jqrm665/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 52, in <module>
        File "/private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-install-mkwggp38/matplotlib_bf1db5bfeb594e288d5e6e7815b52832/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ~~~~~~~~~~~~^^
        File "/private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-install-mkwggp38/matplotlib_bf1db5bfeb594e288d5e6e7815b52832/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
        File "/private/var/folders/zl/38cc_56j5w1f2v_xbx8mv6600000gn/T/pip-install-mkwggp38/matplotlib_bf1db5bfeb594e288d5e6e7815b52832/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


 BTW, I am using the Mac OS, and the python version is Python 3.13.1

Please let me know if you require additional information.

Best regards,
Yujie

**Comment by stefmolin** [comment]
Hi @Yujie29800 &ndash; Python 3.13 is not supported. The error you are getting is probably because the versions of packages we install aren't compatible with it. Please use Python 3.8 or Python 3.9, and if you aren't sure how to install a second version of Python, I would recommend you follow the `conda` instructions as that will take care of it for you.

**Comment by Yujie29800** [comment]
> Hi @Yujie29800 – Python 3.13 is not supported. The error you are getting is probably because the versions of packages we install aren't compatible with it. Please use Python 3.8 or Python 3.9, and if you aren't sure how to install a second version of Python, I would recommend you follow the `conda` instructions as that will take care of it for you.

Thanks Stefanie! I have installed the anaconda, but it still didn't  work. Here is the screenshot:
![56d27e79a904bdd47617bc70adb74c12](https://github.com/user-attachments/assets/6ca25c05-d5d6-4feb-8aa8-9f1ad16cb92f)

It seems like something wrong with the ./visual-aids. So I tried to delete the ./visual-aids in requirements.txt, and then install this requirements.txt. It still didn't work. Here is the screenshot:
![d7e2b5bf5dec056fff69dabb91d83128](https://github.com/user-attachments/assets/d225ed01-6262-41fe-a88d-82630bc306a7)

**Comment by Sinansi** [comment]
Using the latest version of Python is not a good idea. I would suggest waiting atleast one year before installing the latest version. Python 3.13 was released in October 2024, I would suggest installing it in October 2025. You need to wait because the release requires time to stabilize and for libraries to update their requirements.

**Comment by Yujie29800** [comment]
Thanks Stefanie! I have installed anaconda and create an environment with Python 3.9 (conda create --name book_env python=3.9), but there's still something wrong with installing the requirements.txt. Please check the screenshot:
![image](https://github.com/user-attachments/assets/6cff2575-58ee-4b31-bf31-d7360581722b)
and the python version is 3.9.21

**Comment by stefmolin** [comment]
Please create the environment from `environment.yml` (do not use `requirements.txt`): https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by Yujie29800** [comment]
Thank you so much, Stefanie! It worked!!!
